const whatsapp='212670969192';
const products=[
['Dino IPTV',[10,19,29,39],1,'Affordable worldwide IPTV with stable playback and fast activation.'],['Lion OTT',[10,19,29,39],1,'Family-focused entertainment with broad device compatibility.'],['Crystal IPTV',[10,19,29,39],1,'Anti-freeze delivery, broad channels and straightforward setup.'],['Nexon IPTV',[10,19,29,39],1,'Fast European-focused IPTV with extensive on-demand options.'],['Magnum OTT',[10,19,29,39],5,'USA-focused premium OTT with up to five simultaneous connections.'],['Mega OTT',[10,19,29,39],3,'Versatile OTT with smooth live channels and up to three connections.'],['Infinity IPTV',[20,40,55,75],2,'Premium sports, movies and worldwide channels for up to two connections.'],['Trex IPTV',[13,25,29.99,49.99],1,'Popular premium IPTV with a large 4K and 8K-ready library.'],['8K Strong',[13,25,29.99,49.99],1,'High-resolution global IPTV for sports, films and live entertainment.'],['Tivione IPTV',[13,25,29.99,49.99],1,'TiviMate-compatible service designed for reliable family viewing.'],['Ultra 8K',[12,23,33,49],1,'Ultra-high-definition worldwide IPTV with 4K and 8K-ready options.'],['Dream 24K',[12,23,33,49],1,'Premium international IPTV with vivid quality and responsive support.']
];
const reseller=[
['Dino IPTV',120,99],['Trex IPTV',120,185],['Nexon IPTV',120,79],['Ultra 8K',120,190],['8K Strong',120,190],['Dream 24K',120,139],['Lion OTT',10,79],['Crystal IPTV',10,79],['Magnum OTT',10,129],['Mega OTT',10,99],['Infinity IPTV',10,195],['Tivione IPTV',10,190]
];
const logos={'8K Strong':'8kstrong.webp','Crystal IPTV':'crystaliptv.webp','Dino IPTV':'dinoiptv.webp','Dream 24K':'dream24k.webp','Infinity IPTV':'infinityiptv.webp','Lion OTT':'lionott.webp','Magnum OTT':'magnumott.webp','Mega OTT':'megaott.webp','Nexon IPTV':'nexoniptv.webp','Tivione IPTV':'tivioneiptv.webp','Trex IPTV':'trexiptv.webp','Ultra 8K':'ultra8k.webp'};
const selected={};
function order(name,type,details){open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(`Hello, I want ${name} ${type}: ${details}. Please send payment and activation details.`)}`,'_blank','noopener')}
function price(base,count){return base*count*(1-({2:.05,3:.1,4:.15,5:.2}[count]||0))}
function productCard(p){const [name,prices,max,description]=p,count=selected[name]||1,periods=['1 Month','3 Months','6 Months','12 Months'];return `<article><div class="product-head"><img class="product-logo" src="/${logos[name]}" width="68" height="68" loading="lazy" decoding="async" alt="${name} subscription logo" onerror="this.hidden=true"><div><h3>${name}</h3><small>Premium subscription</small></div></div><p>${description}</p>${max>1?`<div class="connection-picker">${Array.from({length:max},(_,i)=>i+1).map(n=>`<button class="${n===count?'active':''}" data-product="${name}" data-count="${n}">${n}${n>1?` · -${{2:5,3:10,4:15,5:20}[n]}%`:''}</button>`).join('')}</div>`:''}<div class="prices">${prices.map((base,i)=>{const total=price(base,count);return `<button data-order="${name}|subscription|${periods[i]}, ${count} connection(s), €${total.toFixed(2)}"><small>${periods[i]} · ${count} conn.</small><b>€${total.toFixed(2)}</b></button>`}).join('')}</div><div class="catalog-foot"><span>Up to ${max} connection${max>1?'s':''}</span><button data-order="${name}|free trial|test account">Free trial →</button></div></article>`}
function renderSubscriptions(){document.querySelector('#subscriptionsGrid').innerHTML=products.map(productCard).join('')}
function renderResellers(){document.querySelector('#resellersGrid').innerHTML=reseller.map(([name,credits,start])=>`<article><div class="product-head"><img class="product-logo" src="/${logos[name]}" width="68" height="68" loading="lazy" decoding="async" alt="${name} reseller logo" onerror="this.hidden=true"><div><h3>${name} Reseller</h3><small>Official reseller panel</small></div></div><p>Wholesale credits, trial creation, customer lines and professional account-management tools.</p><div class="prices"><button data-order="${name}|reseller panel|${credits} credits, €${start}"><small>Starter · ${credits} credits</small><b>€${start}</b></button><button data-order="${name}|reseller panel|custom credit package"><small>Larger packages</small><b>Contact Sales</b></button></div><div class="catalog-foot"><span>Dashboard + trials</span><button data-order="${name}|reseller inquiry|custom package">Ask sales →</button></div></article>`).join('')}
function renderDirectory(){document.querySelector('#directoryGrid').innerHTML=products.map(([name,,,description])=>`<article><h3>${name}</h3><p>${description}</p><a href="/subscriptions">Subscription plans →</a><br><a href="/reseller-panels">Reseller credits →</a></article>`).join('')}
const faq=[['What is 8KStream?','8KStream is the website and comparison brand, not the name of an IPTV server.'],['Can I request a free trial?','Free-trial availability depends on the selected product and current server policy.'],['Which devices are supported?','Popular options include Smart TV, Firestick, Android, Apple devices, computers, TV boxes and compatible MAG devices.'],['How do multi-connections work?','They allow the selected number of simultaneous streams under one package.'],['How fast is activation?','Activation is normally processed after payment and order details are confirmed.'],['Do you offer reseller panels?','Yes. Starter reseller prices and larger contact-sales packages are listed on the reseller page.']];
function renderFaq(){document.querySelector('#faqList').innerHTML=faq.map(([q,a])=>`<article><button aria-expanded="false">${q}<span>＋</span></button><div>${a}</div></article>`).join('')}
function applyRoute(){const path=location.pathname.replace(/\/$/,'')||'/';const section=document.querySelector(`[data-route="${path}"]`);if(path!=='/'&&section)setTimeout(()=>section.scrollIntoView({block:'start'}),0)}
const translations={
en:['Premium IPTV subscriptions.','Professional reseller panels.','Join viewers and resellers worldwide with premium subscriptions, professional reseller tools, flexible connections, and support around the clock.','Engineered for effortless viewing','Choose your IPTV subscription','Start and scale your IPTV business','Questions, answered'],
ar:['اشتراكات IPTV مميزة.','لوحات موزعين احترافية.','انضم إلى المشاهدين والموزعين حول العالم مع اشتراكات مميزة واتصالات مرنة ودعم متواصل.','مصمم لمشاهدة سهلة','اختر اشتراك IPTV المناسب','ابدأ وطور مشروع IPTV الخاص بك','الأسئلة الشائعة'],
es:['Suscripciones IPTV premium.','Paneles profesionales para revendedores.','Planes premium, herramientas de reventa, conexiones flexibles y soporte continuo.','Diseñado para una experiencia sencilla','Elige tu suscripción IPTV','Inicia y amplía tu negocio IPTV','Preguntas frecuentes'],
de:['Premium IPTV-Abonnements.','Professionelle Reseller-Panels.','Premium-Abonnements, flexible Verbindungen, Reseller-Werkzeuge und laufender Support.','Für müheloses Streaming entwickelt','Wähle dein IPTV-Abonnement','Starte und skaliere dein IPTV-Geschäft','Häufige Fragen'],
zh:['高级 IPTV 订阅。','专业经销商面板。','提供高级订阅、灵活连接、经销商工具和全天候支持。','专为轻松观看而设计','选择您的 IPTV 订阅','启动并扩展您的 IPTV 业务','常见问题']};
function setLanguage(lang){const t=translations[lang]||translations.en;document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';const h1=document.querySelector('.hero h1');h1.innerHTML=`${t[0]}<br><span>${t[1]}</span>`;document.querySelector('.hero .lead').textContent=t[2];document.querySelector('#features h2').textContent=t[3];document.querySelector('#subscriptions h2').textContent=t[4];document.querySelector('#reseller-panels h2').textContent=t[5];document.querySelector('#faq h2').textContent=t[6];localStorage.setItem('language',lang)}
document.addEventListener('click',e=>{const picker=e.target.closest('[data-product]');if(picker){selected[picker.dataset.product]=Number(picker.dataset.count);renderSubscriptions();return}const target=e.target.closest('[data-order]');if(target){const [name,type,details]=target.dataset.order.split('|');order(name,type,details);return}const faqButton=e.target.closest('.faq button');if(faqButton){const article=faqButton.parentElement,openState=article.classList.toggle('open');faqButton.setAttribute('aria-expanded',openState);return}const local=e.target.closest('a[href^="/"]');if(local&&['/features','/devices','/subscriptions','/reseller-panels','/iptv-guide','/server-directory','/faq','/'].includes(local.getAttribute('href'))){e.preventDefault();history.pushState({},'',local.href);applyRoute();document.querySelector('#mobileNav').classList.remove('open')}});
document.querySelector('#menuButton').addEventListener('click',e=>{const openState=document.querySelector('#mobileNav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',openState)});
document.querySelector('#language').addEventListener('change',e=>setLanguage(e.target.value));
addEventListener('popstate',applyRoute);document.querySelector('#year').textContent=new Date().getFullYear();renderSubscriptions();renderResellers();renderDirectory();renderFaq();const savedLanguage=localStorage.getItem('language')||'en';document.querySelector('#language').value=savedLanguage;setLanguage(savedLanguage);applyRoute();
